#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/cmovcc.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/movsx.h"
#include "data-mov/movzb.h"
#include "data-mov/movzw.h"
#include "data-mov/cltd.h"
#include "data-mov/push.h"
#include "data-mov/pop.h"
#include "data-mov/lgdt.h"
#include "data-mov/lidt.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/cmp.h"
#include "arith/sub.h"
#include "arith/add.h"
#include "arith/adc.h"
#include "arith/sbb.h"

#include "intr/int.h"
#include "intr/iret.h"
#include "intr/cli.h"
#include "intr/sti.h"

#include "io/in.h"
#include "io/hlt.h"
#include "io/out.h"


#include "control/jmp.h"
#include "control/call.h"
#include "control/jcc.h"
#include "control/ret.h"
#include "control/leave.h"



#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/shr.h"
#include "logic/shl.h"
#include "logic/sar.h"
#include "logic/test.h"
#include "logic/setcc.h"
#include "logic/shrd.h"
#include "logic/bt.h"

#include "string/rep.h"
#include "string/movs.h"
#include "string/stos.h"
#include "string/cmps.h"
#include "string/scas.h"
#include "string/lods.h"

#include "misc/misc.h"
#include "misc/std.h"
#include "misc/cld.h"

#include "special/special.h"
